package qa

import (
	"fmt"
	"regexp"
	"strings"
)

// groupToArea maps a Fleet owning-group label to the smoke-test subdirectory.
var groupToArea = map[string]string{
	"#g-software":      "software",
	"#g-mdm":           "mdm",
	"#g-orchestration": "orchestration",
}

var nonSlug = regexp.MustCompile(`[^a-z0-9]+`)

// GenerateSpec produces a Playwright regression test from a report, matching the
// repo's conventions (authenticated-test fixture, tests/smoke/<area>/<file>).
// Returns the repo-relative path (under tools/qa/playwright) and the file body.
//
// Without an LLM this is a scaffold: it navigates to the reproduced route and
// asserts the generic Fleet error is gone — a real regression guard the author
// then tightens to the specific element. (With a key the agent writes fuller
// assertions.)
func GenerateSpec(rep *Report) (relPath, content string) {
	area := groupToArea[rep.Group]
	if area == "" {
		area = "smoke"
	}
	slug := slugify(rep.Title)
	relPath = fmt.Sprintf("tests/smoke/%s/regression-%d-%s.spec.ts", area, rep.Number, slug)

	route := rep.Route
	if route == "" {
		route = "/dashboard"
	}
	classification := rep.ReleaseStatus
	if classification == "" {
		classification = "n/a"
	}

	var b strings.Builder
	fmt.Fprintf(&b, `import { test, expect } from "../../../helpers/authenticated-test";

// Regression test for fleetdm/fleet#%d
// %s
//
// Verdict: %s on %s (rev %s). Classification: %s.
// Generated by Fleet QA Studio against %s — review and tighten the assertions
// to the specific element from the repro before committing.
test.describe("#%d — %s", () => {
  test("regression: the reported bug stays fixed", async ({ page }) => {
    await page.goto("%s");

    // The page must render without Fleet's generic error fallback.
    await expect(page.locator("body")).not.toContainText("Something's gone wrong");

    // TODO: assert the specific fixed behavior from the investigation, e.g.
    //   await expect(page.getByText("Add category to assign software to it")).toBeVisible();
  });
});
`, rep.Number, rep.Title, rep.Status, shortVer(rep.Version), short(rep.Rev), classification,
		rep.Instance, rep.Number, jsSafe(clipTitle(rep.Title, 60)), route)
	return relPath, b.String()
}

func slugify(s string) string {
	s = nonSlug.ReplaceAllString(strings.ToLower(s), "-")
	s = strings.Trim(s, "-")
	if len(s) > 50 {
		s = strings.Trim(s[:50], "-")
	}
	if s == "" {
		s = "regression"
	}
	return s
}

func clipTitle(s string, n int) string {
	if len(s) > n {
		return strings.TrimSpace(s[:n]) + "…"
	}
	return s
}

// jsSafe makes a string safe to embed inside a double-quoted JS string literal.
func jsSafe(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return s
}
